services:
#    formation.example:
#        class: FormationBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

  formation.hello.generate_form:
        class: FormationBundle\GenerateForm\HelloBlockFormStrategy
        arguments:
            - '%open_orchestra_backoffice.block_default_configuration%'
        tags:
            - { name: open_orchestra_backoffice.generate_form.strategy }
  formation.hello.display_block:
        class: FormationBundle\DisplayBlock\HelloBlockDisplayStrategy
        tags:
            - { name: open_orchestra_display.display_block.strategy }
  formation.hello.display_icon:
        class: FormationBundle\DisplayIcon\HelloBlockDisplayIconStrategy
        tags:
            - { name: open_orchestra_backoffice.display_icon.strategy }

  formation.api_client.transformer:
        class: FormationBundle\Transformer\ApiClientFormationTransformer
        arguments:
            - 'FormationBundle\Facade\ApiClientFormationFacade'
        tags:
            - { name: open_orchestra_api.transformer.strategy }

  formation.api_client.collection.transformer:
        class: FormationBundle\Transformer\ApiClientCollectionFormationTransformer
        arguments:
            - 'FormationBundle\Facade\ApiClientCollectionFormationFacade'
        tags:
            - { name: open_orchestra_api.transformer.strategy }

  formation.form.genre_type:
        class: FormationBundle\Form\GenreType
        tags:
            - { name: form.type, alias: formation_genre_type }